### ISSUE TITLE
Sizing Issue

### ISSUE THREAD

**Issue by lauramosher** [mileszs/wicked_pdf#261]
Hello,

It looks like my styles are not be respected / something is completely shrinking the PDF into ridiculously tiny sizes. I tried to disable smart resizing and all that did was skew the header and footer. The only thing that changed on my end in the app was a merge & bundle update.

Any ideas on why it wouldn't be recognizing or adhering to our styles? I looks like it's about one size smaller all around & and it is not respecting the header tags (they look like normal text).

My pdf specific CSS/LESS is below.

``` css
@import "blue_steel";

body {
  background-color: @base;
}

// This is my "hack" to get my table rows to break properly.
.page-break {
  page-break-inside: avoid;
}

table {
  .striped-table();

  width: 100%;

  td {
    .pad-sides();
  }

  td > address {
    margin: 0;
  }

  td:first-child, th:first-child {
    width: 160px;
  }

  td:nth-child(2), th:nth-child(2) {
    width: 80px;
  }

  td:nth-child(3), th:nth-child(3) {
    width: 80px;
  }

  td:nth-child(5), th:nth-child(5) {
    width: 240px;
  }

  td:last-child, th:last-child {
    width: 120px;
  }
}

.demographics-title {
  .clearfix();
  dl {
    margin: 0;

    dt {
      float: left;
    }
    dd {
      float: right;
    }
  }
}

.demographics-provider-header {
  .pad-all();
  .margin-bottom();

  background-color: @baseMed;
  border: 1px solid @baseMin;

  h4 {
    text-align: left;
    font-weight: bold;
  }

  .person-count {
    text-align: center;
    h2 {
      color: @accentAlt;
    }
  }
}
```

And the relevant blue_steel css:

``` css
body {
  background-color: @baseMed;
  max-width: @bodyMaxWidth;
  min-width: @bodyMinWidth;
  margin: 0 auto;
  font: 14px/20px 'OpenSansRegular', Helvetica, "Arial Unicode MS", Arial, sans-serif;
  font: .875rem/1.25rem 'OpenSansRegular', Helvetica, "Arial Unicode MS", Arial, sans-serif;
}

h1, h2, h3, h4 { font-family: 'OpenSansSemibold'; }

// H2-style headers
.large-header, h2 {
  font-size: 24px;
  line-height: 30px;
  font-size: 1.5rem;
  line-height: 1.875rem;
}

// H4-style headers
.small-header, h4 {
  font-size: 14px;
  line-height: 20px;
  font-size: 1rem;
  line-height: 1.25rem;
}

.margin-bottom { margin-bottom: @defaultMargin; }
.pad-sides { padding: 0 @halfGutter; }
.pad-all { padding: @baseline @halfGutter; }

.clearfix {
  *zoom: 1;
  &:before,
  &:after {
    display: table;
    content: "";
    // Fixes Opera/contenteditable bug:
    // http://nicolasgallagher.com/micro-clearfix-hack/#comment-36952
    line-height: 0;
  }
  &:after {
    clear: both;
  }
}

.striped-table {
  tbody {
    tr.stripe {
      background: @baseLess;
    }

    & > tr:nth-child(odd) {
      background: @baseLess;
    }

    td, th {
      border-right: 1px solid @base;
    }
  }

  &.grouped-rows {
    tbody {
      &.stripe {
        background: @baseLess;
      }

      &:nth-of-type(odd) {
        background: @baseLess;
      }
    }
  }
}
```

To note: It recognizes some stuff, like colors and the table striping. It is adhering to the widths of the table rows, but all of the font sizes and such are shrinking.
