### ISSUE TITLE
wicked pdf with custom fonts

### ISSUE THREAD

**Issue by maaris** [mileszs/wicked_pdf#334]
Hello!
I am using wicked_pdf gem for the pdf generation! There is some problems using custom fonts. I have tried using it like this:

``` css
@font-face {
    font-family:'ITC Franklin Gothic STD';
    font-weight:300;
    font-style:normal;
    src:font-url('itcfranklingothicstd-book.eot');
    src:font-url('itcfranklingothicstd-book.eot?#iefix') format('embedded-opentype'),
        font-url('itcfranklingothicstd-book.woff') format('woff'),
        font-url('itcfranklingothicstd-book.ttf') format('truetype'),
        font-url('itcfranklingothicstd-book.svg#iefix') format('svg');
    }
```

I even tried to convert convert font to base64 but without success.

``` css
@font-face {
    font-family: 'ITC Franklin Gothic STD';
    font-style: normal;
    font-weight: 300;
    src: url(data:font/opentype;charset=utf-8;base64,d09GRgABAAAAAD00AA4A---[large string ommited]----3MAuAH/hbAEjQA=) format("woff"),
    url(data:font/truetype;charset=utf-8;base64,AAEAAAARAQAABAAQRFNJRwAAAAEAAJUIAAA---[large string ommited]-----wAAAAAAAAAAAAEAAAAA) format("truetype");
}
```

Should it work by default or am i missing something?

**Comment by ldrbrandon** [comment]
@unixmonkey I'm trying to use/embed Open Sans light, regular and bold in a pdf. Currently I use the same method you suggested in this post with an absolute url. I have also tried the base64 encoding the reference and that seemed to work as well. The issue however, is that I specify them with different names,
ie: @font-face {  font-family: 'Open Sans Light'; ...  }
@font-face {  font-family: 'Open Sans Regular'; ...  }
@font-face {  font-family: 'Open Sans Bold'; ...  }
But in production it only ever uses regular and bold. and in my css file, when I want a specific element to be a certain one, I use "font-famil: 'Open Sans Light' !important;" and those elements still just get rendered as regular. Even when I specify bold on certain elements, it makes it regular.

Any solutions to this? I feel like I can't be the first one to experience this.

**Comment by unixmonkey** [comment]
I'm not 100% sure, but this looks like it might help:
http://stackoverflow.com/a/25533201/23915

It seems to me from reading a handful of pages that browsers don't all ship with Open Sans Light variant, so you'll need to download or include it yourself, or use Google Fonts, then use CSS to specify the font-weight yourself:

```css
body {
  font-family: 'Open Sans';
  font-style: Light;
}
```

Let me know how it goes!
