### ISSUE TITLE
Page Break not working.

### ISSUE THREAD

**Issue by fazelmk** [mileszs/wicked_pdf#401]
css

.page_break {
  display: block;
  clear: both;
  page-break-after: always;
}

html
<div class="page_break"></div>

Tried using in style and using other html element tags too.

Also there is anyway to know how many pages there gonna be??
So I can dynamically set a page break to make the last page not so clean. I got only one line of text in the last one, so I would like to mate the last paragraph go to the last page if the number of pages is equals to 2.

**Comment by unixmonkey** [comment]
This is the css I use to control page-breaking:
```css
div.alwaysbreak { page-break-before: always; }
div.nobreak:before { clear:both; }
div.nobreak{ page-break-inside: avoid; }
```

These classes won't work on certain types of elements, but they always seem to work for divs, so wrap your paragraphs with `<div class="nobreak">`, and it it can fit on one page, it will, but if the last line of a paragraph crosses the page border, the entire paragraph will be shifted to page2.

Other than that, you could calculate the height of the element with javascript and see if it is tall enough to cross the page boundary, and if so, resize the text or adjust the line-height or something, but that seems very fiddly and error prone.
