### ISSUE TITLE
Dynamic height header/footer

### ISSUE THREAD

**Issue by dsmalko** [mileszs/wicked_pdf#415]
How do I adjust header/footer height (margin) automaticaly by it's contents?

**Comment by unixmonkey** [comment]
I can't think of a way to do it with margins.

I was thinking it might be possible if you make it have 0 margin, and insert the headers/footers afterward using javascript, but keeping track of where to place them sounds like a nightmare.

You might be able to create a bunch of fixed-height and width divs (more than you need) to the exact size of the page (Letter, A4), separate them into different pages with the css:
```css
.break { page-break-before: always; }
``` and use JS to pour the headers, footers, and content into them (from a hidden element?), and float the headers/footers with:
```css
.header { float: top; }
.footer { float: bottom; }
```

Another solution might be to create multiple PDFs with differing margin sizes and stitch them together with `pdftk` when done (like your cover page has different margins from the rest of the document).

Let me know how it goes!
