### ISSUE TITLE
ActionView::Template::Error (undefined method `start_with?' for nil:NilClass):

### ISSUE THREAD

**Issue by muhammadn** [mileszs/wicked_pdf#470]
I am having this error undefined method `start_with?' - I don't understand what this means. where am i loading a nil object?

```
I, [2015-12-01T22:21:00.925951 #5340]  INFO -- : ***************WICKED***************
I, [2015-12-01T22:21:01.102353 #5340]  INFO -- :   Rendered orders/show.erb (175.6ms)
I, [2015-12-01T22:21:01.102604 #5340]  INFO -- : Completed 500 Internal Server Error in 178ms (Models: 0.2ms)
F, [2015-12-01T22:21:01.103737 #5340] FATAL -- : 
    ActionView::Template::Error (undefined method `start_with?' for nil:NilClass):
        2: <html>
        3:   <head>
        4:     <meta charset='utf-8' />
        5:     <%= wicked_pdf_stylesheet_link_tag 'application' %>
        6:     <%= wicked_pdf_javascript_include_tag 'application' %>
        7:   </head>
        8:   <body onload='number_pages'>
      app/views/orders/show.erb:5:in `_app_views_orders_show_erb__4409957572708346332_51152780'
      app/controllers/orders_controller.rb:51:in `block (2 levels) in show'
      app/controllers/orders_controller.rb:48:in `show'
```

**Comment by unixmonkey** [comment]
The error is coming from https://github.com/mileszs/wicked_pdf/blob/master/lib/wicked_pdf/wicked_pdf_helper/assets.rb#L21

trying to parse an `url()` somewhere in your stylesheet against this regex:

`/url\(['"]?([^'"]+?)['"]?\)/`

Could you possibly find which `url` it doesn't like and paste here? Does it have quotes or extra spaces inside the parentheses?

**Comment by muhammadn** [comment]
````
@font-face {
  font-family: 'Glyphicons Halflings';
  src: url('../fonts/glyphicons-halflings-regular.eot');
  src: url('../fonts/glyphicons-halflings-regular.eot?#iefix') format('embedded-opentype'), url('../fonts/glyphicons-halflings-regular.woff2') format('woff2'), url('../fonts/glyphicons-halflings-regular.woff') format('woff'), url('../fonts/glyphicons-halflings-regular.ttf') format('truetype'), url('../fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular') format('svg');
}
````

note that the path of the glyphicons fonts does not exist and those fonts are not there, thus a "nil:NilClass" error in generating the PDF.

I am using cosmo.css from http://bootswatch.com which is a pretty simple template.

**Comment by unixmonkey** [comment]
What it your resolution, or what do you think should happen here?

Does it work if you use the `sass-rails` helper `asset-url` like this?

```css
@font-face {
  font-family: 'Glyphicons Halflings';
  src: asset-url('fonts/glyphicons-halflings-regular.eot');
  src: asset-url('fonts/glyphicons-halflings-regular.eot?#iefix') format('embedded-opentype'), asset-url('fonts/glyphicons-halflings-regular.woff2') format('woff2'), asset-url('fonts/glyphicons-halflings-regular.woff') format('woff'), asset-url('fonts/glyphicons-halflings-regular.ttf') format('truetype'), asset-url('fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular') format('svg');
}
```

**Comment by EvanMcEwen** [comment]
I'm having the same error. I'm using a flat CSS file with no sass pre-compilation so asset-url wouldn't help. I simply remove the '..' from the url. This might break the glyphicon fonts in the PDF generation but I'm not using them so I don't care at the moment. This error only occurred since upgrading from wicked_pdf 0.11.0 to 1.0.3

**Comment by Chaoste** [comment]
I had the same error until I red the solution by EvanMcEwen. I'm NOT using "url" in my CSS file, but I'm using "../app/[...]" for going back in the directory to my CSS file. The solution is adding a leading /.

documents_controller.rb
```rails
        # WickedPDF looks for stylesheet files in #{Rails.root}/public so I have to go back
        @tmp_vars[:css_file] = "/../app/views/documents/styles.css"
        pdf = WickedPdf.new.pdf_from_string(render_to_string(
            'documents/Dienstreiseantrag.html.erb',
            :layout => false,
            :locals => @tmp_vars))
```

Dienstreiseantrag.html.erb

```html
<html>
<head>
<meta charset="utf-8">
<title>Urlaubsantrag (Ausdruck auf weissem Papier mit Logo)</title>
<%= wicked_pdf_stylesheet_link_tag css_file %>
</head>
```

**Comment by kreintjes** [comment]
I am experiencing the same problem. In our stylesheet we include the Bootstrap styling (using SASS `@import "bootstrap";`). Apparently it contains an asset-url which causes problems in combination with WickedPDF.

**Comment by Haseeb717** [comment]
I am experiencing the same issue.How I resolve it?

**Comment by BroiSatse** [comment]
Unfortunately I am not able to reproduce it. If anyone experiencing this issue could contact me via broisatse@gmail.com, we could probably debug this together.

**Comment by victorngkp** [comment]
This may not be an ideal solution, but here's what I did to solve this problem: keep your CSS absolute, with no `@include` or any relative reference.

**Comment by EvanMcEwen** [comment]
@Chaoste Thanks for this! I finally had to upgrade the gem so I came back here and saw your post. Solved the problem for me and shouldn't break anything! :+1:

**Comment by jarmo** [comment]
I had this problem like this:

```css
/* application.css.scss */
@import "style";
```

```css
/* style.css.scss */
.bg-image-2 {
  background: url("../images/bg-image-2.jpg") 50% 0px no-repeat;
}
```

Problem existed even when I commented that `background` property completely out. Problem was solved by removing that style altogether - it was okay solution to me because this style was unused.

Maybe this all helps to fix this problem.
