### ISSUE TITLE
Provide Page Breaks

### ISSUE THREAD

**Issue by ishouvik** [mileszs/wicked_pdf#523]
Hello,
I wonder if it is possible to give page breaks within the html code?

**Comment by unixmonkey** [comment]
You can by applying CSS to elements like this:

```css
div.alwaysbreak { page-break-before: always; }
div.nobreak:before { clear:both; }
div.nobreak { page-break-inside: avoid; }
```

Or like this:

```html
<div style="page-break-after: always;"></div>
```

I'm surprised I've never added anything about this to the README before now, and your question has inspired me to add it!
https://github.com/mileszs/wicked_pdf#page-breaks

Let me know if you have any further questions or issues!
