### ISSUE TITLE
[SOLVED] Intermittently Generating Corrupt / Damaged PDFs

### ISSUE THREAD

**Issue by brunzino** [mileszs/wicked_pdf#607]
This was a tough one for me, so I thought I'd document it for others. 

I generate PDF's from user entered data and every once in a while would get a corrupted file. After a while, I figured out that it was a case of nested "no-break" div's. (Which are pointless anyway, but something to look for if you're encountering this maddening problem). 

Further explanation: 

In order to prevent page-breaks in the middle of a section, I assign a class `no-break` with the following rules: 

``` css
.no-break:before {
  display: block;
  clear: both;
  overflow: hidden;
}
.no-break {
  page-break-inside: avoid !important;
  overflow: visible;
}
```

And the following HTML formatting: 

```html
<div class="no-break">
  .... some user supplied content
  <div class="no-break">
    .... more user supplied content 
  </div>
</div>
```

If the inner `div.no-break` needs to be moved onto the next page to avoid a break, it will corrupt the PDF. 

Hope this helps someone!
