### ISSUE TITLE
Page numbering folow content of page trouble 

### ISSUE THREAD

**Issue by VoTaiTri** [mileszs/wicked_pdf#708]
I'm try to print list tables, 
with next table, i'll break page
with table have many rows, i'll break page
and i want to count page number folow content of table
i'll count page by the end of table, not by the end of page
ex:
******************
_page1_
content of table 1
******************

******************
_page2_
content of table 1
end of table 1

1 (page number)
******************

******************
_page3_
content of table 2
end of table 2

2 (page number)
******************
in ex ablove, we have 3 pages, but page number count up to 2
i can do it, but i can't set possition for page numbering folow this way
i want to set it in bottom of page, so this's my css

```css
  .page_number {
    text-align: center;
    font-size: 14px;
    padding-bottom: 5px;
    margin-bottom: 5px;
  }

  .page-break {
    display: block;
    clear: both;
    page-break-before: avoid;
  }
```

but page number was printed after the end of table, i want to it's bottom of page
i need your help, thanks!
